[package]
name = "mazi_billiards_fractal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
heapless = "0.8.0"
rusty-ppm = "0.3.0"
simple-canvas = "0.1.1"
